---

services:
  nginx:
    image: $NGINX_IMAGE
    container_name: $NGINX_NAME
    ports:
      - "80:80"
    volumes:
      - ./webroot:/usr/share/nginx/html:ro

  certbot:
    image: $CERTBOT_IMAGE
    container_name: $CERTBOT_NAME
    volumes:
      - ./certs:/etc/letsencrypt            # Хранилище для сертификатов
      - ./certbot-log:/var/log/letsencrypt  # Логи certbot
      - ./webroot:/var/www/html             # Каталог для webroot валидации
    command: >
      certonly --webroot
      --webroot-path=/var/www/html
      --email $USER_EMAIL
      --agree-tos
      --no-eff-email
      -d $DOMAIN_NAME
      -d www.$DOMAIN_NAME
